/*======================================================================

   zero coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef OVER__H
#define OVER__H


#define OVER_BITMAP_WIDTH   1024
#define OVER_BITMAP_HEIGHT  64
#define OVER_NUM_IMAGES   10


		//	Format:
		//	U,V,Width,Height



const unsigned int over_texcoords[] = {
 0,0, 200, 39,				// 0
 0, 39, 200, 39,				// 1
};


#endif
