/*======================================================================

   zero coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef NUM__H
#define NUM__H


#define NUM_BITMAP_WIDTH   1024
#define NUM_BITMAP_HEIGHT  64
#define NUM_NUM_IMAGES   10


		//	Format:
		//	U,V,Width,Height



const unsigned int num_texcoords[] = {
 0,0, 64, 64,				// 0
 64, 0, 64, 64,				// 1
 128, 0, 64, 64,				// 2
 192, 0, 64, 64,				// 3
 256, 0, 64, 64,				// 4
 320, 0, 64, 64,				// 5
 384, 0, 64, 64,				// 6
 448, 0, 64, 64,				// 7
 512, 0, 64, 64,				// 8
 576, 0, 64, 64,				// 9
};


#endif
